# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Whois-RegistryFusion
version:      0.01
version_from: lib/Net/Whois/RegistryFusion.pm
installdirs:  site
requires:
    Date::Format:                  
    Error:                         
    File::Slurp:                   
    File::stat:                    
    IO::LockedFile:                
    LWP::Simple:                   
    Module::Signature:             
    Test::More:                    
    Test::Signature:               

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
